---
stages:
- name: Build flow
  inputs:
  - type: git
    branch: master
    service: ${SAMPLE_REPO}
  triggers:
  - type: commit
  jobs:
  - name: Build driver
    type: builder
    artifact_dir: target
    build_type: maven
    script: |-
        #!/bin/bash
        export JAVA_HOME=$JAVA8_HOME
        mvn -B -Pstreams-runner package

        echo "CF_APP_NAME=${CF_APP_NAME}"
        echo "PIPELINE_API_KEY=${API_KEY}"
        echo "PIPELINE_SA_INSTANCE=$(echo -e "${SA_INSTANCE}" | tr -d '[:space:]')"
        echo "PIPELINE_MH_INSTANCE=$(echo -e "${MH_INSTANCE}" | tr -d '[:space:]')"
        echo "COS_SECRET_ACCESS_KEY=${COS_SECRET}"
        echo "COS_ACCESS_KEY_ID=${COS_KEY}"
        echo "PIPELINE_COS_BUCKET=${COS_BUCKET}"
        echo "PIPELINE_COS_ENDPOINT=${COS_ENDPOINT}"

- name: Deploy flow to development
  inputs:
  - type: job
    stage: Build flow
    job: Build driver
  triggers:
  - type: stage
  jobs:
  - name: Deploy flow
    type: deployer
    deploy_type: customimage
    target:
      region_id: ${PROD_REGION_ID}
      organization: ${PROD_ORG_NAME}
      space: ${PROD_SPACE_NAME}
      application: ${CF_APP_NAME}
    script: |
      #!/bin/bash
      # Push app

      echo $region_id
      if [[ $PIPELINE_COS_ENDPOINT != \"* ]]; then
        PIPELINE_COS_ENDPOINT=\"$PIPELINE_COS_ENDPOINT\"
      fi

      if [[ $PIPELINE_COS_BUCKET != \"* ]]; then
        PIPELINE_COS_BUCKET=\"$PIPELINE_COS_BUCKET\"
      fi

      if [[ $COS_ACCESS_KEY_ID != \"* ]]; then
        COS_ACCESS_KEY_ID=\"$COS_ACCESS_KEY_ID\"
      fi

      if [[ $COS_SECRET_ACCESS_KEY != \"* ]]; then
        COS_SECRET_ACCESS_KEY=\"$COS_SECRET_ACCESS_KEY\"
      fi

      echo "generating vcap.json"
            echo "{
              \"streaming-analytics\":[{
                \"name\" : \"streaming-analytics\",
                \"credentials\" : $PIPELINE_SA_INSTANCE
              }],
              \"messagehub\": $PIPELINE_MH_INSTANCE,
              \"cos\": {
                \"accessKeyId\": $COS_ACCESS_KEY_ID,
                \"secretKey\": $COS_SECRET_ACCESS_KEY,
                \"endpoint\": $PIPELINE_COS_ENDPOINT,
                \"bucket\": $PIPELINE_COS_BUCKET,
                \"filePrefix\": \"$CF_APP_NAME\"
              }
            }" > vcap.json

      cat ./vcap.json

      java -cp ./example-starter-kit-0.1-SNAPSHOT.jar:./dependency/com.ibm.streams.beam-1.2.1/com.ibm.streams.beam/lib/com.ibm.streams.beam.translation.jar \
            com.ibm.streams.beam.sample.datahistorian.DataHistorian \
            --runner=StreamsRunner \
            --contextType=STREAMING_ANALYTICS_SERVICE \
            --vcapServices=./vcap.json \
            --serviceName=streaming-analytics \
            --beamToolkitDir=./dependency/com.ibm.streams.beam-1.2.1 \
            --jarsToStage=./example-starter-kit-0.1-SNAPSHOT.jar \
            --jobName=$CF_APP_NAME
    docker_image: maven:3.5.3-ibmjava
